homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret ha_key
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret ha_url

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor: !include_dir_merge_list sensor

# Text to speech
tts:

# Cloud
cloud:

# Climate
climate: !include_dir_merge_list climate

# Media Players
media_player: !include_dir_merge_list mediaplayer

# Device Trackers
device_tracker: !include_dir_merge_list device_tracker

############
# Additional Zones
############
zone:
  name: !secret zone_name
  latitude: !secret zone_latitude
  longitude: !secret zone_longitude
  icon: mdi:briefcase
  radius: 250

zone 2:
  name: !secret zone2_name
  latitude: !secret zone2_latitude
  longitude: !secret zone2_longitude
  icon: mdi:domain
  radius: 250

zone 3:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  icon: mdi:home
  radius: 150

group: !include_dir_merge_named group
automation: !include automations.yaml
script: !include scripts.yaml
